/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class formlogin extends javax.swing.JFrame {

    public Connection con;
    public Statement stt;
    public frommenu frommenu; 
    /*
     * Creates new form NewJFrame
     */
    String acces=null;
    String name=null;
    String query;
    public formlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namatulisan = new javax.swing.JLabel();
        namalogin = new javax.swing.JLabel();
        usernametext = new javax.swing.JLabel();
        passwordtext = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        status = new javax.swing.JComboBox();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Depot Modern V.1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(243, 173, 88));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namatulisan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotulisan.png"))); // NOI18N
        jPanel1.add(namatulisan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        namalogin.setFont(new java.awt.Font("Niagara Solid", 1, 40)); // NOI18N
        namalogin.setForeground(new java.awt.Color(255, 255, 255));
        namalogin.setText("LOG IN");
        jPanel1.add(namalogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, 40));

        usernametext.setFont(new java.awt.Font("Script MT Bold", 0, 27)); // NOI18N
        usernametext.setForeground(new java.awt.Color(255, 255, 255));
        usernametext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_shield_40px.png"))); // NOI18N
        usernametext.setText("Username");
        jPanel1.add(usernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, -1));

        passwordtext.setFont(new java.awt.Font("Script MT Bold", 0, 27)); // NOI18N
        passwordtext.setForeground(new java.awt.Color(255, 255, 255));
        passwordtext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_key_2_40px.png"))); // NOI18N
        passwordtext.setText("Password");
        jPanel1.add(passwordtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, -1));

        username.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 270, 40));

        password.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        password.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 40));

        login.setBackground(java.awt.SystemColor.activeCaption);
        login.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        login.setText("Log in");
        login.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                loginKeyPressed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 100, 40));

        status.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "pegawai" }));
        status.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 150, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 420, 750));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/makanan.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_depot","root","");
            stt = con.createStatement();
            query = "select * from tb_karyawan where User_ID= '"+username.getText()+"' and Pass_ID= '"+String.valueOf(password.getPassword())+"'and Jabatan='"+status.getSelectedItem()+"'";
            ResultSet rss = stt.executeQuery(query);
            if(rss.next()){
                acces = rss.getString("Jabatan");
                UserSession.setacces(acces);
                name = rss.getString("nama_pegawai");
                UserSession.setname(name);
                
                frommenu = new frommenu();
                frommenu.setVisible(true);
                this.dispose();//klu udah berhasil login Form yang ini ketutup
            }else {
                JOptionPane.showMessageDialog(null,"Username dan Password salah");
                username.setText("");
                password.setText("");
            }
            
        }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Ada yang salah dengan sistem");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(formlogin.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
       Autologin();
       }
    }//GEN-LAST:event_loginKeyPressed

    public void Autologin (){
        frommenu = new frommenu();
        frommenu.setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel namalogin;
    private javax.swing.JLabel namatulisan;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordtext;
    private javax.swing.JComboBox status;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernametext;
    // End of variables declaration//GEN-END:variables
}
