/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.JOptionPane;
import project.inputmenubar;
import java.util.HashMap;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author asus
 */
public class tambahmenu extends javax.swing.JFrame {

    Statement stt;
    ResultSet rss;
    Connection con;
    String query;
    /**
     * Creates new form tambahmenu
     */
    public tambahmenu() {
        initComponents();
        koneksi a = new koneksi();
        a.config();
        con = a.con;
        stt = a.stt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logotulisan = new javax.swing.JLabel();
        stokmenutext = new javax.swing.JLabel();
        kodebartext1 = new javax.swing.JLabel();
        namamenutext = new javax.swing.JLabel();
        katagorimenutext = new javax.swing.JLabel();
        hargamenutext = new javax.swing.JLabel();
        kodemenu = new javax.swing.JTextField();
        namamenu = new javax.swing.JTextField();
        hargamenu = new javax.swing.JTextField();
        stokmenu = new javax.swing.JTextField();
        katmenu = new javax.swing.JComboBox();
        edit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Erase = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Depot Modern V.1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logotulisan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotulisan.png"))); // NOI18N
        logotulisan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(logotulisan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));

        stokmenutext.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 12)); // NOI18N
        stokmenutext.setText("STOK MENU                                :");
        getContentPane().add(stokmenutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        kodebartext1.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 12)); // NOI18N
        kodebartext1.setText("KODE MENU                               :");
        getContentPane().add(kodebartext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        namamenutext.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 12)); // NOI18N
        namamenutext.setText("NAMA MENU                              :");
        getContentPane().add(namamenutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        katagorimenutext.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 12)); // NOI18N
        katagorimenutext.setText("KATEGORI MENU                      :");
        getContentPane().add(katagorimenutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        hargamenutext.setFont(new java.awt.Font("Kozuka Gothic Pro B", 1, 12)); // NOI18N
        hargamenutext.setText("HARGA MENU                            :");
        getContentPane().add(hargamenutext, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        kodemenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kodemenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(kodemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 260, 30));

        namamenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        namamenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(namamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 260, 30));

        hargamenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hargamenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(hargamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 260, 30));

        stokmenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        stokmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(stokmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 260, 30));

        katmenu.setBackground(new java.awt.Color(255, 255, 153));
        katmenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        katmenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "makanan", "minuman", "cemilan" }));
        katmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 153, 0)));
        getContentPane().add(katmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 260, 30));

        edit.setBackground(new java.awt.Color(255, 204, 102));
        edit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_30px.png"))); // NOI18N
        edit.setText("Edit");
        edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 70, 40));

        reset.setBackground(new java.awt.Color(255, 204, 102));
        reset.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_24px.png"))); // NOI18N
        reset.setText("Reset");
        reset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 80, 40));

        Erase.setBackground(new java.awt.Color(255, 204, 102));
        Erase.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Erase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_24px.png"))); // NOI18N
        Erase.setText("Erase");
        Erase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EraseActionPerformed(evt);
            }
        });
        getContentPane().add(Erase, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, 40));

        cancel.setBackground(new java.awt.Color(255, 204, 102));
        cancel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_30px.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 80, 40));

        save.setBackground(new java.awt.Color(255, 204, 102));
        save.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_save_30px.png"))); // NOI18N
        save.setText("Save");
        save.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 80, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode menu", "nama makanan", "stok makanan", "harga ", "katagori"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 440, 110));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/makanan.jpg"))); // NOI18N
        bg.setText("jLabel1");
        bg.setPreferredSize(new java.awt.Dimension(1739, 144));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 490, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
      try {
            PreparedStatement pStatement = con.prepareStatement("UPDATE tb_menu SET nama_makanan=?,stok_makanan=?,harga_makanan=?,kode_katagori=? WHERE kode_menu=?");

            pStatement.setString(1, namamenu.getText());
            pStatement.setString(2, stokmenu.getText());
            pStatement.setString(3, hargamenu.getText());
            pStatement.setString(4, (String) katmenu.getSelectedItem());
            pStatement.setString(5, kodemenu.getText());
            
            if ( pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog(this,"Editsukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog(this, "Edit gagal",
                "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

            namamenu.setText("");
            stokmenu.setText("");
            hargamenu.setText("");
            katmenu.setSelectedItem("makanan");
            kodemenu.setText("");
        }
            catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
      ViewData();
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        inputmenubar b = new inputmenubar();
        b.kode_menu = kodemenu.getText();
        b.nama_makanan = namamenu.getText();
        b.stok_makanan = stokmenu.getText();
        b.harga_makanan = hargamenu.getText();
        String katagori= (String) katmenu.getSelectedItem();
        b.kode_katagori = null;
        switch (katagori){
            case"makanan":
                b.kode_katagori ="KTG01";
                break;
            case"minuman":
                b.kode_katagori ="KTG02";
                break;
            case"cemilan":
                b.kode_katagori ="KTG03";
                break;
        }
        try{
            b.simpan();
            JOptionPane.showMessageDialog(null,"berhasil di upload");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        ViewData();
    }//GEN-LAST:event_saveActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        kodemenu.setText(jTable1.getModel().getValueAt(row,0).toString());
        namamenu.setText(jTable1.getModel().getValueAt(row,1).toString());
        stokmenu.setText(jTable1.getModel().getValueAt(row,2).toString());
        hargamenu.setText(jTable1.getModel().getValueAt(row,3).toString());
        String katagori = jTable1.getModel().getValueAt(row,4).toString();
        ambilkatagori(katagori);
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      ViewData();
    }//GEN-LAST:event_formWindowOpened

    private void EraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EraseActionPerformed
     try {
            PreparedStatement pStatement = con.prepareStatement("DELETE FROM tb_menu WHERE kode_menu=?");

            pStatement.setString(1,kodemenu.getText());

            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog
               (this,"Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog
                (this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

            namamenu.setText("");
            stokmenu.setText(""); 
            hargamenu.setText("");
            katmenu.setSelectedItem("makanan");
            kodemenu.setText("");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
        ViewData();

    }//GEN-LAST:event_EraseActionPerformed

    private void reset(){
        namamenu.setText("");
        stokmenu.setText("");
        hargamenu.setText("");
    }
    private void ViewData(){
        inputmenubar b = new inputmenubar();
        try{
            jTable1.setModel(DbUtils.resultSetToTableModel(b.UpdateJTable()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void ambilkatagori(String kode_katagori){
        String[] kt ={"makanan","minuman","cemilan"};
        katmenu.removeAllItems();
        katmenu.addItem(kode_katagori);
        for(int i = 0;i<kt.length;i++){
            if(!kt[i].equals(kode_katagori)){
                katmenu.addItem(kt[i]); }
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tambahmenu t = new tambahmenu();
                t.setVisible(true);
                t.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Erase;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancel;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hargamenu;
    private javax.swing.JLabel hargamenutext;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel katagorimenutext;
    private javax.swing.JComboBox katmenu;
    private javax.swing.JLabel kodebartext1;
    private javax.swing.JTextField kodemenu;
    private javax.swing.JLabel logotulisan;
    private javax.swing.JTextField namamenu;
    private javax.swing.JLabel namamenutext;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField stokmenu;
    private javax.swing.JLabel stokmenutext;
    // End of variables declaration//GEN-END:variables
}
