/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.HashMap;
import net.proteanit.sql.DbUtils;
import project.inputmenubar;
/**
 *
 * @author asus
 */
public class listmenu extends javax.swing.JFrame {
    Statement stt;
    ResultSet rss;
    Connection con;
    koneksi koneksi;
    /**
     * Creates new form listmenu
     */
    public listmenu() {
        
        initComponents();
        koneksi a = new koneksi();
        a.config();
        con = a.con;
        stt = a.stt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namabg = new javax.swing.JLabel();
        idmenutx = new javax.swing.JLabel();
        hrgitmtx = new javax.swing.JLabel();
        ktgtx = new javax.swing.JLabel();
        jmlstoktx = new javax.swing.JLabel();
        nmmenutx = new javax.swing.JLabel();
        ktgkode = new javax.swing.JTextField();
        idmenu = new javax.swing.JTextField();
        nmmenu = new javax.swing.JTextField();
        jmlstok = new javax.swing.JTextField();
        hrgitem = new javax.swing.JTextField();
        carikode = new javax.swing.JButton();
        carinama = new javax.swing.JButton();
        reportbarang = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablecari = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Depot Modern V.1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Charlemagne Std", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("PENCARIAN MENU ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        namabg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotulisan.png"))); // NOI18N
        getContentPane().add(namabg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        idmenutx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idmenutx.setText("Kode Menu                    :");
        getContentPane().add(idmenutx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 20));

        hrgitmtx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hrgitmtx.setText("Harga Item                    :");
        getContentPane().add(hrgitmtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 20));

        ktgtx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ktgtx.setText("Kategori                        :");
        getContentPane().add(ktgtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 150, 20));

        jmlstoktx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jmlstoktx.setText("Jumlah Stok                  :");
        getContentPane().add(jmlstoktx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 20));

        nmmenutx.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nmmenutx.setText("Nama Menu                   :");
        getContentPane().add(nmmenutx, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 150, 20));
        getContentPane().add(ktgkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 190, 30));
        getContentPane().add(idmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 30));
        getContentPane().add(nmmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 30));
        getContentPane().add(jmlstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 30));
        getContentPane().add(hrgitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, 30));

        carikode.setBackground(new java.awt.Color(255, 204, 51));
        carikode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        carikode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_16px.png"))); // NOI18N
        carikode.setText("Kode");
        carikode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        carikode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikodeActionPerformed(evt);
            }
        });
        getContentPane().add(carikode, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 90, 30));

        carinama.setBackground(new java.awt.Color(255, 204, 51));
        carinama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        carinama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_16px.png"))); // NOI18N
        carinama.setText("Nama");
        carinama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        carinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carinamaActionPerformed(evt);
            }
        });
        getContentPane().add(carinama, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 90, 30));

        reportbarang.setBackground(new java.awt.Color(255, 204, 51));
        reportbarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        reportbarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_report_card_16px.png"))); // NOI18N
        reportbarang.setText("Report");
        reportbarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        reportbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbarangActionPerformed(evt);
            }
        });
        getContentPane().add(reportbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 90, 30));

        cancel.setBackground(new java.awt.Color(255, 204, 51));
        cancel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_30px.png"))); // NOI18N
        cancel.setText("Batal");
        cancel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 90, -1));

        tablecari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Menu", "Nama Menu", "Stok Menu", "Harga ", "Kategori"
            }
        ));
        tablecari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablecariMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablecari);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 130));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102), new java.awt.Color(255, 255, 102)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 500, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/makanan.jpg"))); // NOI18N
        bg.setText("jLabel1");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbarangActionPerformed
       try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("barang.jasper"), null, koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_reportbarangActionPerformed

    private void tablecariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablecariMouseClicked
        int row = tablecari.getSelectedRow();
        idmenu.setText(tablecari.getModel().getValueAt(row,0).toString());
        nmmenu.setText(tablecari.getModel().getValueAt(row,1).toString());
        jmlstok.setText(tablecari.getModel().getValueAt(row,2).toString());
        hrgitem.setText(tablecari.getModel().getValueAt(row,3).toString());
        ktgkode.setText(tablecari.getModel().getValueAt(row,4).toString());
        
    }//GEN-LAST:event_tablecariMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ViewData();
    }//GEN-LAST:event_formWindowOpened

    private void carikodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikodeActionPerformed
        try {
            Statement stt = con.createStatement();
            ResultSet rss = stt.executeQuery("Select * from tb_menu" + " where kode_menu='" + idmenu.getText() +"'");
            if (rss.next()) {
                nmmenu.setText(rss.getString("nama_makanan"));
                jmlstok.setText(rss.getString("stok_makanan"));
                hrgitem.setText(rss.getString("harga_makanan"));
                ktgkode.setText(rss.getString("kode_katagori"));
                idmenu.setText(rss.getString("kode_menu"));
            } else {
                JOptionPane.showMessageDialog(this,"ID: Salah","Informasi", JOptionPane.INFORMATION_MESSAGE);

                nmmenu.setText("");
                jmlstok.setText(""); 
                hrgitem.setText("");
                ktgkode.setText("");
                idmenu.setText("");
                nmmenu.requestFocus();
            }
        }
           catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());

        }
ViewData();
    }//GEN-LAST:event_carikodeActionPerformed

    private void carinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carinamaActionPerformed
        try {
            Statement stt = con.createStatement();
            ResultSet rss = stt.executeQuery("Select * from tb_menu" + " where nama_makanan like('%" +nmmenu.getText() + "%')");

            if (rss.next()) {
                nmmenu.setText(rss.getString("nama_makanan"));
                jmlstok.setText(rss.getString("stok_makanan"));
                hrgitem.setText(rss.getString("harga_makanan"));
                ktgkode.setText(rss.getString("kode_katagori"));
                idmenu.setText(rss.getString("kode_menu"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);

                nmmenu.setText("");
                jmlstok.setText(""); 
                hrgitem.setText("");
                ktgkode.setText("");
                idmenu.setText("");
                nmmenu.requestFocus();
            }
        }
           catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
           }
    }//GEN-LAST:event_carinamaActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed
    private void ViewData(){
        inputmenubar b = new inputmenubar();
        try{
            tablecari.setModel(DbUtils.resultSetToTableModel(b.UpdateJTable()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancel;
    private javax.swing.JButton carikode;
    private javax.swing.JButton carinama;
    private javax.swing.JTextField hrgitem;
    private javax.swing.JLabel hrgitmtx;
    private javax.swing.JTextField idmenu;
    private javax.swing.JLabel idmenutx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlstok;
    private javax.swing.JLabel jmlstoktx;
    private javax.swing.JTextField ktgkode;
    private javax.swing.JLabel ktgtx;
    private javax.swing.JLabel namabg;
    private javax.swing.JTextField nmmenu;
    private javax.swing.JLabel nmmenutx;
    private javax.swing.JButton reportbarang;
    private javax.swing.JTable tablecari;
    // End of variables declaration//GEN-END:variables
}
