/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author asus
 */
public class forminputkaryawan extends javax.swing.JFrame {

    Statement stt;
    ResultSet rss;
    Connection con;
    String query;
    /**
     * Creates new form forminputkaryawan
     */
    public forminputkaryawan() {
        initComponents();
        koneksi a = new koneksi();
        a.config();
        con = a.con;
        stt = a.stt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namabg = new javax.swing.JLabel();
        Kodekaryawantext = new javax.swing.JLabel();
        alamattxt = new javax.swing.JLabel();
        namakaryawantxt = new javax.swing.JLabel();
        jeniskelamintxt = new javax.swing.JLabel();
        usertxt = new javax.swing.JLabel();
        passtxt = new javax.swing.JLabel();
        jbtntxt = new javax.swing.JLabel();
        kdkaryawan = new javax.swing.JTextField();
        nmkaryawan = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jnskelamin = new javax.swing.JComboBox();
        jabatan = new javax.swing.JComboBox();
        save = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        carinama = new javax.swing.JButton();
        datareport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatteks = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namabg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logotulisan.png"))); // NOI18N
        getContentPane().add(namabg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 140));

        Kodekaryawantext.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Kodekaryawantext.setForeground(new java.awt.Color(51, 0, 0));
        Kodekaryawantext.setText("Kode Karyawan             :");
        getContentPane().add(Kodekaryawantext, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 20));

        alamattxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        alamattxt.setForeground(new java.awt.Color(51, 0, 0));
        alamattxt.setText("Alamat                          :");
        getContentPane().add(alamattxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 190, -1));

        namakaryawantxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        namakaryawantxt.setForeground(new java.awt.Color(51, 0, 0));
        namakaryawantxt.setText("Nama Karyawan            :");
        getContentPane().add(namakaryawantxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 190, -1));

        jeniskelamintxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jeniskelamintxt.setForeground(new java.awt.Color(51, 0, 0));
        jeniskelamintxt.setText("Jenis Kelamin               :");
        getContentPane().add(jeniskelamintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 190, -1));

        usertxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        usertxt.setForeground(new java.awt.Color(51, 0, 0));
        usertxt.setText("Username                      :");
        getContentPane().add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        passtxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        passtxt.setForeground(new java.awt.Color(51, 0, 0));
        passtxt.setText("New Password               :");
        getContentPane().add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jbtntxt.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jbtntxt.setForeground(new java.awt.Color(51, 0, 0));
        jbtntxt.setText("Jabatan                          :");
        getContentPane().add(jbtntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        kdkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(kdkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 190, 30));

        nmkaryawan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(nmkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 190, 30));

        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 190, 30));

        password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 190, 30));

        jnskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));
        jnskelamin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(jnskelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 190, 30));

        jabatan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "admin", "pegawai", " " }));
        jabatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        getContentPane().add(jabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 190, 30));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_save_30px.png"))); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 90, 40));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_waste_24px.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, -1, 40));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_24px.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, -1, 40));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_cancel_30px.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 110, 40));

        carinama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        carinama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_search_16px.png"))); // NOI18N
        carinama.setText("Search Name");
        carinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carinamaActionPerformed(evt);
            }
        });
        getContentPane().add(carinama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 20));

        datareport.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        datareport.setText("DATA");
        datareport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datareportActionPerformed(evt);
            }
        });
        getContentPane().add(datareport, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 20));

        alamatteks.setColumns(20);
        alamatteks.setRows(5);
        alamatteks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 102)));
        jScrollPane1.setViewportView(alamatteks);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 190, 80));

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        judul.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        judul.setText("INPUT DATA KARYAWAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/makanan.jpg"))); // NOI18N
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
    }//GEN-LAST:event_formWindowOpened

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String kode_pegawai = kdkaryawan.getText();
        String nama_pegawai = nmkaryawan.getText();
        String kelamin1 = (String)jnskelamin.getSelectedItem();
        String kelamin = null;
        switch (kelamin1) {
            case"Laki-laki":
                kelamin ="Laki-laki";
                break;
            case"Perempuan":
                kelamin ="Perempuan";
                break;
        }
        String alamat = alamatteks.getText();
        String User_ID = username.getText();
        String Pass_ID = password.getText();
        String Jabatan1 = (String)jabatan.getSelectedItem();
        String Jabatan = null;
        switch (Jabatan1){
            case"admin":
                Jabatan ="admin";
                break;
            case"pegawai":
                Jabatan ="pegawai";
                break;
        }
        try {
            query ="insert into tb_karyawan values('"+kode_pegawai+"','"+nama_pegawai+"','"+kelamin+"','"+alamat+"','"+User_ID+"','"+Pass_ID+"','"+Jabatan+"')";
            stt.executeUpdate(query);
            JOptionPane.showMessageDialog(this, "Sudah Berhasil","Success",JOptionPane.INFORMATION_MESSAGE);
            reset();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Masukkan Data Kembali"+ e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            PreparedStatement pStatement = con.prepareStatement("DELETE FROM tb_karyawan WHERE kode_pegawai=?");

            pStatement.setString(1,kdkaryawan.getText());

            if (pStatement.executeUpdate()>0)
                JOptionPane.showMessageDialog
               (this,"Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            else
                JOptionPane.showMessageDialog
                (this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);

            pStatement.close();

            nmkaryawan.setText("");
            jnskelamin.setSelectedItem("Laki-laki"); 
            alamatteks.setText("");
            username.setText("");
            password.setText("");
            jabatan.setSelectedItem("admin");
            kdkaryawan.setText("");
        }
        catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void carinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carinamaActionPerformed
       try {
            Statement stt = con.createStatement();
            ResultSet rss = stt.executeQuery("Select * from tb_karyawan" + " where nama_pegawai like('%" +nmkaryawan.getText() + "%')");

            if (rss.next()) {
                nmkaryawan.setText(rss.getString("nama_pegawai"));
                jnskelamin.setSelectedItem(rss.getString("kelamin"));
                alamatteks.setText(rss.getString("alamat"));
                username.setText(rss.getString("User_ID"));
                password.setText(rss.getString("Pass_ID"));
                jabatan.setSelectedItem(rss.getString("Jabatan"));
                kdkaryawan.setText(rss.getString("kode_pegawai"));
            } else {
                JOptionPane.showMessageDialog(this,"Nama: Salah", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);

                nmkaryawan.setText("");
                jnskelamin.setSelectedItem("Laki-laki"); 
                alamatteks.setText("");
                username.setText("");
                password.setText("");
                jabatan.setSelectedItem("admin");
                kdkaryawan.setText("");
                nmkaryawan.requestFocus();
            }
        }
           catch (SQLException e){
            System.out.println("koneksi gagal " + e.toString());
           }
    }//GEN-LAST:event_carinamaActionPerformed

    private void datareportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datareportActionPerformed
        try {
            JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("datakaryawan.jasper"), null, koneksi.getKoneksi());
            JasperViewer.viewReport(jp, false);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_datareportActionPerformed
private void reset(){
    nmkaryawan.setText("");
    kdkaryawan.setText("");
    alamatteks.setText("");
    username.setText("");
    password.setText("");
    jnskelamin.setSelectedItem("Laki-laki");
    jabatan.setSelectedItem("admin");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forminputkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forminputkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forminputkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forminputkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forminputkaryawan().setVisible(true);
                new forminputkaryawan().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Kodekaryawantext;
    private javax.swing.JTextArea alamatteks;
    private javax.swing.JLabel alamattxt;
    private javax.swing.JLabel bg;
    private javax.swing.JButton cancel;
    private javax.swing.JButton carinama;
    private javax.swing.JButton datareport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jabatan;
    private javax.swing.JLabel jbtntxt;
    private javax.swing.JLabel jeniskelamintxt;
    private javax.swing.JComboBox jnskelamin;
    private javax.swing.JLabel judul;
    private javax.swing.JTextField kdkaryawan;
    private javax.swing.JLabel namabg;
    private javax.swing.JLabel namakaryawantxt;
    private javax.swing.JTextField nmkaryawan;
    private javax.swing.JLabel passtxt;
    private javax.swing.JTextField password;
    private javax.swing.JButton reset;
    private javax.swing.JButton save;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usertxt;
    // End of variables declaration//GEN-END:variables
}
